name: sitis-app
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas>=2.0.0
  - numpy>=1.24.0
  - pip
  - pip:
    - streamlit>=1.28.0
    - msal>=1.24.0
    - requests>=2.31.0

